---
- hosts: localhost
  vars:
    domain: nj.drewfus.org
  roles:
    - role: andrewrothstein.pki
      pki_dir: '{{ playbook_dir }}/pki-dir/{{ domain }}'
      pki_names:
        - C: US
          L: Englewood
          O: Drewfus
          OU: WWW
          ST: New Jersey
      pki_ca:
        cname: ca.{{ domain }}
      pki_servers:
        - cname: edge
          sans:
            - edge.{{ domain }}
          altips:
            - 192.168.1.1
        - cname: matchbox
          sans:
            - matchbox.{{ domain }}
          altips:
            - 192.168.1.30
        - cname: freenas
          sans:
            - freenas.{{ domain }}
          altips:
            - 192.168.1.175
        - cname: vault
          sans:
            - vault.{{ domain }}
          altips:
            - 192.168.1.136
