---
- hosts: localhost
  vars:
    domain: nj.drewfus.org
    pkis_dir: '{{ playbook_dir }}/pki-dir'
  roles:
    - role: andrewrothstein.pki
      pki_dir: '{{ pkis_dir }}/{{ domain }}'
      pki_names:
        - C: US
          L: Englewood
          O: Drewfus
          OU: WWW
          ST: New Jersey
      pki_ca:
        expiry: '8760h'
        pathlen: 0
        cname: ca.{{ domain }}
      pki_servers:
        - cname: edge.{{ domain }}
          profile: server
          altips:
            - 192.168.1.1
        - cname: core-001.{{ domain }}
          profile: server
          sans:
            - core-001.{{ domain }}
        - cname: core-002.{{ domain }}
          profile: server
          sans:
            - core-002.{{ domain }}
        - cname: core-003.{{ domain }}
          profile: server
          sans:
            - core-003.{{ domain }}
        - cname: core-004.{{ domain }}
          profile: server
          sans:
            - core-004.{{ domain }}
        - cname: core-005.{{ domain }}
          profile: server
          sans:
            - core-005.{{ domain }}
        - cname: gitlab.{{ domain }}
          profile: server
          sans:
            - gitlab.{{ domain }}
