---
- hosts: localhost
  roles:
    - role: andrewrothstein.pki
      pki_dir: ~/pki/drewfus-org
      pki_names:
        - C: US
          L: Englewood
          O: Drewfus
          OU: WWW
          ST: New Jersey
      pki_ca:
        cname: ca.drewfus.org
      pki_servers:
        - cname: edge.drewfus.org
          altips:
            - 192.168.1.1
        - cname: matchbox.drewfus.org
          altips:
            - 192.168.1.30
        - cname: freenas.drewfus.org
          altips:
            - 192.168.1.125
        - cname: core-0001.drewfus.org
          altips:
            - 192.168.1.128
        - cname: core-0002.drewfus.org
          altips:
            - 192.168.1.129
        - cname: core-0003.drewfus.org
          altips:
            - 192.168.1.131
