---
- hosts: localhost
  roles:
    - role: andrewrothstein.pki
      pki_names:
        - C: US
          L: 'Englewood'
          O: 'Drewfus'
          OU: WWW
          ST: 'New Jersey'
      pki_ca:
        cname: ca.drewfus.org
        altips:
          - 192.168.1.1
      pki_servers:
        - cname: matchbox.drewfus.org
          altips:
            - 192.168.1.109
            - 172.16.0.1
        
        
